import localFont from "next/font/local";
import "../../../styles/main.scss";
import Sidebar from "@/components/backoffice/Sidebar/sidebar";
import Navbar from "@/components/backoffice/Navbar/Navbar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "My Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex">
      {/* sidebar */}
        <Sidebar/>
      
      <div className="w-full">
        {/* header */}
        <Navbar/>
        {/* main */}
        <main className="p-8 bg-[#19192B] text-teal-50 min-h-screen mt-16 ml-60">{children}</main>
      </div>
      {/* main body */}
    </div>
  );
}
